modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"

[[mods]]
modId = "autochefsdelight"
version = "${file.jarVersion}"
displayName = "Autochef's Delight"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/autochefs-delight"
description = ""

[[mixins]]
config = "autochefsdelight.mixins.json"

[[dependencies.autochefsdelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autochefsdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
